"""Build the BinaryFuse16 MD5 whitelist .xf from all_md5.txt.

all_md5.txt (in the project root) contains every distinct MD5 hash from the
NSRL RDS Android database — all extensions, not just APKs — giving maximum
coverage for the on-device whitelist.

The xorfilter_writer binary (BinaryFuse16, ~2.16 bytes/key) converts the
newline-delimited list directly to a tagged .xf asset:

    app/src/main/assets/scan/whitelist.xf

Usage:
    python gen_whitelist_apk.py [path/to/all_md5.txt]

If no argument is given, looks for all_md5.txt in the project root.
"""

import os
import subprocess
import sys
from pathlib import Path

# all_md5.txt is in the project root (generated by extracting every DISTINCT
# lower(md5) from the NSRL METADATA table across base + delta databases).
DEFAULT_MD5_TXT = Path("all_md5.txt")

WRITER = Path("dev-tools/xorfilter_writer/target/release/xorfilter_writer")
if sys.platform == "win32":
    WRITER = WRITER.with_suffix(".exe")

OUT = Path("app/src/main/assets/scan/whitelist.xf")


def build_writer():
    """Compile xorfilter_writer if the release binary is missing."""
    writer_dir = Path("dev-tools/xorfilter_writer")
    print("building xorfilter_writer (release)...")
    subprocess.run(
        ["cargo", "build", "--release"],
        cwd=writer_dir,
        check=True,
    )


def main():
    os.chdir(Path(__file__).parent)
    OUT.parent.mkdir(parents=True, exist_ok=True)

    md5_txt = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_MD5_TXT
    if not md5_txt.exists():
        print(f"ERROR: {md5_txt} not found. Generate it first.", file=sys.stderr)
        sys.exit(1)

    if not WRITER.exists():
        build_writer()

    n_lines = sum(1 for _ in open(md5_txt, "r", encoding="utf-8") if _.strip())
    print(f"Input: {md5_txt} ({n_lines:,} hashes, {md5_txt.stat().st_size:,} bytes)")
    print(f"Building BinaryFuse16 filter -> {OUT} ...")

    subprocess.run(
        [str(WRITER), str(md5_txt), str(OUT)],
        check=True,
    )

    size = OUT.stat().st_size
    print(f"Done: {OUT} = {size:,} bytes ({size / 1_048_576:.1f} MB)")


if __name__ == "__main__":
    main()
